### ISSUE TITLE
Uncaught PDOException

### ISSUE THREAD

**Issue by tcarmean** [SchedulesDirect/mfdb-json#9]
Trying to migrate to API-20141201 I'm getting the following error when getting to this step in the README (every step prior to this completed successfully):

tivo@mythbox:~/mfdb-json$ ./sd-utility.php

Using production server.
Using timezone UTC
sd-utility.php utility program API:20141201 v0.27/2015-07-06
Using database information from ~/.mythtv/config.xml
Connecting to Schedules Direct database.
Connecting to MythTV database.
Checking for database upgrades.
Schema version is 1.
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'schedulesdirect.SDpeople' doesn't exist' in /mnt/tivo/mfdb-json/sd-utility.php:1827
Stack trace:
#0 /mnt/tivo/mfdb-json/sd-utility.php(1827): PDO->exec('ALTER TABLE SDp...')
#1 /mnt/tivo/mfdb-json/sd-utility.php(294): checkDatabase()
#2 {main}
  thrown in /mnt/tivo/mfdb-json/sd-utility.php on line 1827

**Comment by tcarmean** [comment]
Not having any knowledge about how this works I see that the script is trying to alter a table that doesn't exist:

```
    if ($schemaVersion == "1")
    {
        $dbhSD->exec("ALTER TABLE SDpeople ADD INDEX(name)");
        settingSD("SchedulesDirectJSONschemaVersion", "2");
    }
```

```
mysql> show tables;
+---------------------------+
| Tables_in_schedulesdirect |
+---------------------------+
| credits                   |
| imageCache                |
| lineups                   |
| messages                  |
| people                    |
| programGenres             |
| programRating             |
| programs                  |
| schedules                 |
| settings                  |
+---------------------------+
10 rows in set (0.00 sec)
```

**Comment by rkulagowski** [comment]
I will look into it. Thanks.

**Comment by tcarmean** [comment]
@rkulagowski: I managed to get around it by updating the line of code in question. Once I get through the entire setup process successfully I'll submit a PR for you to review. :smiley_cat:

**Comment by rkulagowski** [comment]
Thanks - that will help.
